" All system-wide defaults are set in $VIMRUNTIME/debian.vim (usually just
" /usr/share/vim/vimcurrent/debian.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vim/vimrc), since debian.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing debian.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim
" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
syntax on 
filetype  indent on
"filetype  plugin on
"set number

" colorscheme choose
colorscheme desert

" Tlist plugin config 
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1

let Tlist_GainFocus_On_ToggleOpen = 1
"let Tlist_Close_On_Select 				= 1

let tlist_make_settings  = 'make;m:makros;t:targets'
let tlist_qmake_settings = 'qmake;t:SystemVariables'

" winmanager config
let g:winManagerWindowLayout='FileExplorer|TagList'
"nmap wm :b!1<CR>:only!<CR>:e!~/.vim/file.tmp<CR>:WMToggle<CR>:b!1<CR><C-w>H<C-w>l<C-w>l<C-w>J:resize 1<CR><C-w>k<C-w>h:vertical resize 75<CR><C-l>w:resize 15<CR><C-w>h<C-w>k:b!1<CR>
nmap wm :b!1<CR>:only!<CR>:resize 200<CR>:e!~/.vim/file.tmp<CR>:WMToggle<CR>:b!1<CR><C-w>k<C-w>J:resize 1<CR><C-w>k<C-w>l<C-w>H:vertical resize 95<CR><C-l><C-k>w:resize 15<CR><C-w>h<C-w>k:b!1<CR>

" cscope config
set cscopequickfix=s-,c-,d-,i-,t-,e-
" cscopekeymap
nmap <C-_>s :cs find s <C-R>=expand("<cword>")<CR><CR>
nmap <C-_>g :cs find g <C-R>=expand("<cword>")<CR><CR>
nmap <C-_>c :cs find c <C-R>=expand("<cword>")<CR><CR>
nmap <C-_>t :cs find t <C-R>=expand("<cword>")<CR><CR>
nmap <C-_>e :cs find e <C-R>=expand("<cword>")<CR><CR>
nmap <C-_>f :cs find f <C-R>=expand("<cfile>")<CR><CR>
nmap <C-_>i :cs find i ^<C-R>=expand("<cfile>")<CR>$<CR>
nmap <C-_>d :cs find d <C-R>=expand("<cword>")<CR><CR>

" minibufexplorer config
let g:miniBufExplMapCTabSwitchBufs = 1 
let g:miniBufExplMapWindowNavVim = 1 
let g:miniBufExplMapWindowNavArrows = 1 
let g:miniBufExplModSelTarget = 1
" let g:miniBufExplorerMoreThanOne=0

" a.vim config (key map)
nnoremap <silent> <F12> :A<CR>

" grep.vim config
nnoremap <silent> <F6> :Rgrep<CR>
nnoremap <silent> <F7> :!clear && sdcv -n <cword><CR>

" c.vim config
" let g:C_Ctrl_j = 0 

" complete
"filetype plugin indent on 
"set completeopt=longest,menu 
"let g:SuperTabRetainCompletionType=52
"let g:SuperTabDefaultCompletionType="<C-X><C-O>"

" encodeing config
let &termencoding=&encoding
set fileencodings=utf-8,gbk,gb2312,ucs-bom,cp936

" map exit key
nmap ZZ :wqall<CR>
nmap <C-c> :qa!<CR>
" noremap  <C-Esc>       :close<CR>
"inoremap  <C-Esc>  <C-C>:close<CR>
"nnoremap  <C-q>    :wqall<CR>



" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
set incsearch		" Incremental search
set autowrite		" Automatically save before commands like :next and :make
set hidden             " Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes) in terminals

"set autoindent                  " copy indent from current line
set autoread                    " read open files again when changed outside Vim
set backspace=indent,eol,start  " backspacing over everything in insert mode
set browsedir=current           " which directory to use for the file browser
set complete+=k                 " scan the files given with the 'dictionary' option
set history=50                  " keep 50 lines of command line history
set listchars=tab:>.,eol:\$     " strings to use in 'list' mode
"set nowrap                      " do not wrap lines
set popt=left:8pc,right:3pc     " print options
set ruler                       " show the cursor position all the time
set showcmd                     " display incomplete commands
"set smartindent                 " smart autoindenting when starting a new line
set wildignore=*.bak,*.o,*.e,*~ " wildmenu: ignore these extensions
set wildmenu                    " command-line completion in an enhanced mode
"set nowrap                      " do not wrap lines
"set shiftwidth=2                " number of spaces to use for each step of indent
"set backup                      " keep a backup file
"set tabstop=2                   " number of spaces that a <Tab> counts for
"set hlsearch                    " highlight the last used search pattern
"set visualbell                  " visual bell instead of beeping


" addtiong vimrc
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif


" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark
"# // The switch of the Source Explorer                                         "
                                                                              "
" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
"    \| exe "normal g'\"" | endif
"endif

" Uncomment the following to have Vim load indentation rules according to the
" detected filetype. Per default Debian Vim only load filetype specific
" plugins.
"if has("autocmd")
"  filetype indent on
"endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes) in terminals

" Source a global configuration file if available
" XXX Deprecated, please move your changes here in /etc/vim/vimrc
